### ISSUE TITLE
IDs make re-usable component.....hard to re-use :)

### ISSUE THREAD

**Issue by seigel** [ZakMcRae/poster-counts#1]
https://github.com/ZakMcRae/poster-counts/blob/d4212c3e2709cfa5f90cf1ff95f102b0ea067be8/src/components/InputRow.js#L59

I find this quite a clever way to handle this issue.  Clever, sometimes has consequence.  Since you are leveraging IDs on the DOM elements, you would be violating the DOM contract  of  "ids must be unique" if you were to have two items in inventory.  I am just nitpicking because I want to see how you think.  Is there another way you could have done this?

What kinds of things would you have to consider in general if you were supporting n-items on your grid, and how would that "Circle" area need to be wired in to make it work as an overall gauge?

**Comment by ZakMcRae** [comment]
I was originally thinking of giving each item a unique product id(poster object in state still has it as 001) that I would combine with the input element name with a separator of some sort like a : and set that as the html id. Later I would do a e.target.id.split(':') which would give me my projuct id and the input element to properly modifiy that specific one spot in the state. Would possibly also have to account for sizes like you mentioned but that could also be added with a separator before doing the split.

This was more of me cutting a corner for this demo to save time as I feared I was already taking too long. This is something I can still fix and refactor.
